name: DingTalk Notify
on:
  workflow_dispatch: # manual trigger
  release:
    types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Setup Node
            uses: actions/setup-node@v3
            with:
              node-version: '18'
          - name: Setup Environment
            run: node -e "console.log('PACKAGE_VERSION=' + require('./package.json').version + '\nPACKAGE_NAME=' + require('./package.json').name + '-' + require('./package.json').version)" >> $GITHUB_ENV # set PACKAGE_VERSION and PACKAGE_NAME            
          - name: Read Changelog
            id: changelog
            uses: mindsers/changelog-reader-action@v2
            with:
              version: ${{ env.PACKAGE_VERSION }}
              path: ./CHANGELOG.md
          - name: Notify
            uses: zcong1993/actions-ding@master
            with:
              dingToken: ${{ secrets.DING_TALK_ACCESS_TOKEN}}
              body: |
                {
                    "msgtype": "markdown",
                    "markdown": {
                        "title":"👏👏 TSwagger Release Successful",
                        "text": "### vscode-tswagger \n\n**tswagger@${{ env.PACKAGE_VERSION }}** had been published. These are the changes:\n\n${{ steps.changelog.outputs.changes }}"
                    },
                    "at": {
                        "isAtAll": false
                    }
                }